
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author GAURAV
 */
public class AddPrescriptions extends javax.swing.JFrame {

    private int did;

    public AddPrescriptions(int did) {
        initComponents();
        this.did = did;
        showData();
    }

    /**
     * Creates new form DoctorPrescription
     */
    public AddPrescriptions() {
        initComponents();
    }

    private void showData() {
        var db = new Database();

        try {
            PreparedStatement stmt = db.con.prepareStatement("select * from doctor where did = ?");
            stmt.setInt(1, did);

            ResultSet rs = stmt.executeQuery();

            rs.next();

            lbldoctorid.setText(String.valueOf(rs.getInt(1)));
            lbldoctorname.setText(rs.getString(2));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     *
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txtpid = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtage = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Buttonadd = new javax.swing.JButton();
        Buttonclear = new javax.swing.JButton();
        Buttonhome = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtbloodgroup = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tareaprescription = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tareaadvice = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        tareapathology = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        tarearemark = new javax.swing.JTextArea();
        Buttonview = new javax.swing.JButton();
        Buttonupdate = new javax.swing.JButton();
        lbldoctorid = new javax.swing.JLabel();
        lbldoctorname = new javax.swing.JLabel();
        Buttonfeatch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("HOSPITAL MANAGEMENT SYSTEM");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("  PATIENT PRESCRIPTIONS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(279, 279, 279)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(316, 316, 316)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("NAME");

        txtname.setEditable(false);
        txtname.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        txtpid.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("PID");

        txtage.setEditable(false);
        txtage.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("AGE");

        Buttonadd.setBackground(new java.awt.Color(51, 51, 51));
        Buttonadd.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Buttonadd.setForeground(new java.awt.Color(255, 255, 255));
        Buttonadd.setText("ADD");
        Buttonadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonaddActionPerformed(evt);
            }
        });

        Buttonclear.setBackground(new java.awt.Color(51, 51, 51));
        Buttonclear.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Buttonclear.setForeground(new java.awt.Color(255, 255, 255));
        Buttonclear.setText("CLEAR");
        Buttonclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonclearActionPerformed(evt);
            }
        });

        Buttonhome.setBackground(new java.awt.Color(51, 51, 51));
        Buttonhome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Buttonhome.setForeground(new java.awt.Color(255, 255, 255));
        Buttonhome.setText("HOME");
        Buttonhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonhomeActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("BLOOD GROUP");

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("PRESCRIPTIONS ");

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("PATHOLOGY");

        txtbloodgroup.setEditable(false);
        txtbloodgroup.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("REMARK ");

        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setText("ADVICE");

        jLabel19.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19.setText("DOCTOR NAME  :");

        jLabel20.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 51, 51));
        jLabel20.setText("DOCTOR ID         :");

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 28)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("  PATIENT INFORMATIONS");
        jLabel3.setOpaque(true);

        jLabel21.setBackground(new java.awt.Color(0, 0, 0));
        jLabel21.setFont(new java.awt.Font("Century Gothic", 1, 28)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("  PATIENT PRESCRIPTIONS");
        jLabel21.setOpaque(true);

        tareaprescription.setColumns(20);
        tareaprescription.setRows(5);
        jScrollPane1.setViewportView(tareaprescription);

        tareaadvice.setColumns(20);
        tareaadvice.setRows(5);
        jScrollPane2.setViewportView(tareaadvice);

        tareapathology.setColumns(20);
        tareapathology.setRows(5);
        jScrollPane3.setViewportView(tareapathology);

        tarearemark.setColumns(20);
        tarearemark.setRows(5);
        jScrollPane4.setViewportView(tarearemark);

        Buttonview.setBackground(new java.awt.Color(51, 51, 51));
        Buttonview.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Buttonview.setForeground(new java.awt.Color(255, 255, 255));
        Buttonview.setText("VIEW");
        Buttonview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonviewActionPerformed(evt);
            }
        });

        Buttonupdate.setBackground(new java.awt.Color(51, 51, 51));
        Buttonupdate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Buttonupdate.setForeground(new java.awt.Color(255, 255, 255));
        Buttonupdate.setText("UPDATE");
        Buttonupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonupdateActionPerformed(evt);
            }
        });

        lbldoctorid.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbldoctorid.setText("...................");

        lbldoctorname.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbldoctorname.setText("...................");

        Buttonfeatch.setBackground(new java.awt.Color(51, 51, 51));
        Buttonfeatch.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Buttonfeatch.setForeground(new java.awt.Color(255, 255, 255));
        Buttonfeatch.setText("FEATCH");
        Buttonfeatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonfeatchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 657, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(41, 41, 41))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(143, 143, 143)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtpid, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtage, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(51, 51, 51)
                                .addComponent(txtbloodgroup, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Buttonfeatch, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(351, 351, 351)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel19))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbldoctorid, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbldoctorname, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(Buttonadd)
                        .addGap(66, 66, 66)
                        .addComponent(Buttonview)
                        .addGap(43, 43, 43)
                        .addComponent(Buttonupdate)
                        .addGap(48, 48, 48)
                        .addComponent(Buttonclear)
                        .addGap(77, 77, 77)
                        .addComponent(Buttonhome)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(301, 301, 301))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(lbldoctorid))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(lbldoctorname))
                .addGap(38, 38, 38)
                .addComponent(jLabel3)
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Buttonfeatch, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtbloodgroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtpid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addGap(35, 35, 35)
                .addComponent(jLabel21)
                .addGap(24, 24, 24)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Buttonclear)
                    .addComponent(Buttonadd)
                    .addComponent(Buttonhome)
                    .addComponent(Buttonview)
                    .addComponent(Buttonupdate))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonaddActionPerformed
        if (txtpid.getText().isEmpty() || txtage.getText().trim().isEmpty() || txtname.getText().trim().isEmpty() || txtbloodgroup.getText().trim().isEmpty() || tareaprescription.getText().trim().isEmpty() || tareapathology.getText().trim().isEmpty() || tarearemark.getText().trim().isEmpty() || tareaadvice.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "One or more fields are empty");
            return;
        }
        String pid = txtpid.getText();
        int age = Integer.parseInt(txtage.getText());
        String name = txtname.getText();
        String bloodgroup = txtbloodgroup.getText();
        String prescriptions = tareaprescription.getText();
        String pathology = tareapathology.getText();
        String remark = tarearemark.getText();
        String advice = tareaadvice.getText();
        String did = lbldoctorid.getText();
        String dname = lbldoctorname.getText();
        if (pid.trim().isEmpty() || txtage.getText().trim().isEmpty() || name.trim().isEmpty() || bloodgroup.trim().isEmpty() || prescriptions.trim().isEmpty() || pathology.trim().isEmpty() || remark.trim().isEmpty() || advice.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "One or more fields are empty");
            return;
        }

// ... Existing code ...
// All fields are filled and valid, proceed with further code
        try {
            Database db = new Database();

            String query = "INSERT INTO prescriptions (did, dname, pid, age, pname, bloodgroup, prescriptions, pathology, remark, advice) VALUES (?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement pst = db.con.prepareStatement(query);

            // Set parameter values
            pst.setString(1, did);
            pst.setString(2, dname);
            pst.setString(3, pid);
            pst.setInt(4, age);
            pst.setString(5, name);
            pst.setString(6, bloodgroup);
            pst.setString(7, prescriptions);
            pst.setString(8, pathology);
            pst.setString(9, remark);
            pst.setString(10, advice);

            int aa = pst.executeUpdate();
            if (aa == 1) {
                JOptionPane.showMessageDialog(this, "Add Success");

                // Clear UI components
                txtpid.setText("");
                txtage.setText("");
                txtname.setText("");
                txtbloodgroup.setText("");
                tareaprescription.setText("");
                tareapathology.setText("");
                tarearemark.setText("");
                tareaadvice.setText("");
            } else {
                JOptionPane.showMessageDialog(null, "Something went wrong");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

// ... Rest of the code ...
    }//GEN-LAST:event_ButtonaddActionPerformed

    private void ButtonclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonclearActionPerformed
        // Clear UI components
        txtpid.setText("");
        txtage.setText("");
        txtname.setText("");
        txtbloodgroup.setText("");
        tareaprescription.setText("");
        tareapathology.setText("");
        tarearemark.setText("");
        tareaadvice.setText("");
    }//GEN-LAST:event_ButtonclearActionPerformed

    private void ButtonhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonhomeActionPerformed
//     new DoctorDashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ButtonhomeActionPerformed

    private void ButtonviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonviewActionPerformed
        // TODO add your handling code here:
        String pid = txtpid.getText();

        try {
            Database db = new Database();

            String query = "SELECT age, pname, bloodgroup, prescriptions, pathology, remark, advice FROM prescriptions WHERE pid=?";
            PreparedStatement pst = db.con.prepareStatement(query);

            // Set parameter value
            pst.setString(1, pid);

            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                int age = rs.getInt("age");
                String name = rs.getString("pname");
                String bloodgroup = rs.getString("bloodgroup");
                String prescriptions = rs.getString("prescriptions");
                String pathology = rs.getString("pathology");
                String remark = rs.getString("remark");
                String advice = rs.getString("advice");

                // Update UI components with retrieved data
                txtage.setText(String.valueOf(age));
                txtname.setText(name);
                txtbloodgroup.setText(bloodgroup);
                tareaprescription.setText(prescriptions);
                tareapathology.setText(pathology);
                tarearemark.setText(remark);
                tareaadvice.setText(advice);
            } else {
                JOptionPane.showMessageDialog(null, " Patient Not Prescribed");
            }

            rs.close();
            pst.close();
            db.con.close();
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_ButtonviewActionPerformed

    private void ButtonupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonupdateActionPerformed
        // TODO add your handling code here:
        if (txtpid.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter Patient ID");
            return;
        }
        int pid = Integer.parseInt(txtpid.getText());;
        int age = Integer.parseInt(txtage.getText());
        String name = txtname.getText();
        String bloodgroup = txtbloodgroup.getText();
        String prescriptions = tareaprescription.getText();
        String pathology = tareapathology.getText();
        String remark = tarearemark.getText();
        String advice = tareaadvice.getText();
        String did = lbldoctorid.getText();
        String dname = lbldoctorname.getText();

        try {
            Database db = new Database();

            String query = "UPDATE prescriptions SET age=?, pname=?, bloodgroup=?, prescriptions=?, pathology=?, remark=?, advice=? WHERE pid=?";
            PreparedStatement pst = db.con.prepareStatement(query);

            // Set parameter values
            pst.setInt(1, age);
            pst.setString(2, name);
            pst.setString(3, bloodgroup);
            pst.setString(4, prescriptions);
            pst.setString(5, pathology);
            pst.setString(6, remark);
            pst.setString(7, advice);
            pst.setInt(8, pid);

            int rowsAffected = pst.executeUpdate();
            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(this, "Update Success");

                // Clear UI components
                txtpid.setText("");
                txtage.setText("");
                txtname.setText("");
                txtbloodgroup.setText("");
                tareaprescription.setText("");
                tareapathology.setText("");
                tarearemark.setText("");
                tareaadvice.setText("");
            } else {
                JOptionPane.showMessageDialog(null, " Record Not found");
            }

            pst.close();
            db.con.close();
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_ButtonupdateActionPerformed

    private void ButtonfeatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonfeatchActionPerformed
        if (txtpid.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter Patient ID");
            return;
        }
        try {
            Database db = new Database();

            String pid = txtpid.getText();

            String query = "SELECT * FROM patient WHERE pid = ?";
            PreparedStatement pst = db.con.prepareStatement(query);
            pst.setString(1, pid);

            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                int age = rs.getInt("age");
                String pname = rs.getString("pname");
                String bloodgroup = rs.getString("bloodgroup");

                // Process fetched data as needed
                // Example: Print data to console
                txtage.setText(String.valueOf(age));
                txtname.setText(pname);
                txtbloodgroup.setText(bloodgroup);
            }

            // Close ResultSet, PreparedStatement, and database connection
            rs.close();
            pst.close();
            db.con.close();
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_ButtonfeatchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddPrescriptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddPrescriptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddPrescriptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddPrescriptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddPrescriptions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buttonadd;
    private javax.swing.JButton Buttonclear;
    private javax.swing.JButton Buttonfeatch;
    private javax.swing.JButton Buttonhome;
    private javax.swing.JButton Buttonupdate;
    private javax.swing.JButton Buttonview;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lbldoctorid;
    private javax.swing.JLabel lbldoctorname;
    private javax.swing.JTextArea tareaadvice;
    private javax.swing.JTextArea tareapathology;
    private javax.swing.JTextArea tareaprescription;
    private javax.swing.JTextArea tarearemark;
    private javax.swing.JTextField txtage;
    private javax.swing.JTextField txtbloodgroup;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtpid;
    // End of variables declaration//GEN-END:variables
}
