
import java.awt.print.PrinterException;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author GAURAV
 */
public class Discharge extends javax.swing.JFrame {

    /**
     * Creates new form Discharge
     */
    public Discharge() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void clear() {

        txtname.setText("");
        txtsurgerytype.setText("");
        txtsurgeryamount.setText("");
        txtroomtype.setText("");
        txtroomrent.setText("");
        Datechooserdate.setText("");
        txtdays.setText("");
        txtpid.setText("");
        txtage.setText("");
        txtbloodgroup.setText("");
        txtdoctorname.setText("");
        txtconsultantfee1.setText("");
        jTextArea1.setText("");

    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Buttonreport = new javax.swing.JButton();
        Buttonprint = new javax.swing.JButton();
        txtname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Buttonclear = new javax.swing.JButton();
        txtdoctorname = new javax.swing.JTextField();
        txtroomrent = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtroomtype = new javax.swing.JTextField();
        txtsurgerytype = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        Buttonfeatch = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtpid = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtsurgeryamount = new javax.swing.JTextField();
        Datechooserdate = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtconsultantfee1 = new javax.swing.JTextField();
        txtdays = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtage = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtbloodgroup = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        Buttonhome = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        Buttonreport.setBackground(new java.awt.Color(51, 51, 51));
        Buttonreport.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Buttonreport.setForeground(new java.awt.Color(255, 255, 255));
        Buttonreport.setText("REPORT");
        Buttonreport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonreportActionPerformed(evt);
            }
        });

        Buttonprint.setBackground(new java.awt.Color(51, 51, 51));
        Buttonprint.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Buttonprint.setForeground(new java.awt.Color(255, 255, 255));
        Buttonprint.setText("PRINT");
        Buttonprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonprintActionPerformed(evt);
            }
        });

        txtname.setEditable(false);
        txtname.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("DOCTOR NAME");

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("NAME");

        Buttonclear.setBackground(new java.awt.Color(51, 51, 51));
        Buttonclear.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Buttonclear.setForeground(new java.awt.Color(255, 255, 255));
        Buttonclear.setText("CLEAR");
        Buttonclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonclearActionPerformed(evt);
            }
        });

        txtdoctorname.setEditable(false);
        txtdoctorname.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        txtroomrent.setEditable(false);
        txtroomrent.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("ROOM TYPE");

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("SURGERY TYPE");

        txtroomtype.setEditable(false);
        txtroomtype.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        txtsurgerytype.setEditable(false);
        txtsurgerytype.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("ROOM RENT");

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setName("SUMMERY"); // NOI18N
        jScrollPane2.setViewportView(jTextArea1);

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("PATIENT INFORMATION");

        Buttonfeatch.setBackground(new java.awt.Color(51, 51, 51));
        Buttonfeatch.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Buttonfeatch.setForeground(new java.awt.Color(255, 255, 255));
        Buttonfeatch.setText("FEATCH");
        Buttonfeatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonfeatchActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("PID");

        txtpid.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("HOSPITAL MANAGEMENT SYSTEM");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("DISCHARGE AREA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(408, 408, 408)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(340, 340, 340)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("SURGERY AMOUNT ");

        txtsurgeryamount.setEditable(false);
        txtsurgeryamount.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        Datechooserdate.setEditable(false);
        Datechooserdate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Datechooserdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DatechooserdateActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("CONSULTANT FEE");

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("ADMIT DATE ");

        txtconsultantfee1.setEditable(false);
        txtconsultantfee1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtconsultantfee1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtconsultantfee1ActionPerformed(evt);
            }
        });

        txtdays.setEditable(false);
        txtdays.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtdays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdaysActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText(" TOTAL DAYS");

        txtage.setEditable(false);
        txtage.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("AGE");

        txtbloodgroup.setEditable(false);
        txtbloodgroup.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("BLOOD GROUP");

        Buttonhome.setBackground(new java.awt.Color(51, 51, 51));
        Buttonhome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Buttonhome.setForeground(new java.awt.Color(255, 255, 255));
        Buttonhome.setText("HOME");
        Buttonhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonhomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel14))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtdoctorname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(txtconsultantfee1)
                                    .addComponent(Datechooserdate)
                                    .addComponent(txtage)
                                    .addComponent(txtname)
                                    .addComponent(txtpid))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Buttonfeatch)
                                .addGap(105, 105, 105)
                                .addComponent(Buttonreport)
                                .addGap(78, 78, 78)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtsurgerytype, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel10)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(jLabel11)
                                                    .addGap(30, 30, 30))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(Buttonprint, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel13))
                                                    .addGap(87, 87, 87)))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtdays)
                                                .addComponent(Buttonclear)
                                                .addComponent(txtsurgeryamount, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtroomtype, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addGap(64, 64, 64)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtbloodgroup, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtroomrent, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(242, 242, 242)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(Buttonhome, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtpid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)))
                            .addComponent(txtroomtype, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7)
                            .addComponent(txtroomrent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtbloodgroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15))
                                .addGap(59, 59, 59)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtsurgerytype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtsurgeryamount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(txtage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(64, 64, 64)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtconsultantfee1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtdoctorname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(61, 61, 61)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Datechooserdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtdays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Buttonclear)
                            .addComponent(Buttonprint)
                            .addComponent(Buttonfeatch)
                            .addComponent(Buttonreport)
                            .addComponent(Buttonhome)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonreportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonreportActionPerformed

        StringBuilder report = new StringBuilder();

// Add hospital bill details
        report.append("-------- Hospital Bill --------\n");
        report.append("Doctor Name: ").append(txtdoctorname.getText()).append("\n");
        report.append("Patient ID: ").append(txtpid.getText()).append("\n");
        report.append("Patient Name: ").append(txtname.getText()).append("\n");
        report.append("Patient Age: ").append(txtage.getText()).append("\n");
        report.append(" Blood Group: ").append(txtbloodgroup.getText()).append("\n");
        report.append("Surgery Type: ").append(txtsurgerytype.getText()).append("\n");
        report.append("Surgery Amount: ").append(txtsurgeryamount.getText()).append("\n");
        report.append("Consultant Fee: ").append(txtconsultantfee1.getText()).append("\n");
        report.append("Admit Date: ").append(Datechooserdate.getText()).append("\n");
        report.append("Room Type: ").append(txtroomtype.getText()).append("\n");
        report.append("Room Rent: ").append(txtroomrent.getText()).append("\n");
        report.append("Duration (Days): ").append(txtdays.getText()).append("\n");

        double surgeryAmount = Double.parseDouble(txtsurgeryamount.getText());
        double roomRent = Double.parseDouble(txtroomrent.getText());
        double ConsultantFee = Double.parseDouble(txtconsultantfee1.getText());
        int days = Integer.parseInt(txtdays.getText());
        double totalCost = ConsultantFee + surgeryAmount + (roomRent * days);
        double gst = totalCost * 0.18;

        report.append("\n");
        report.append("-------- Bill Summary --------\n");
        report.append("Total Cost: ").append(totalCost).append("\n");
        report.append("GST (18%): ").append(gst).append("\n");
        report.append("Total Amount (including GST): ").append(totalCost + gst).append("\n");

        jTextArea1.setText(report.toString());

    }//GEN-LAST:event_ButtonreportActionPerformed

    private void ButtonprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonprintActionPerformed
        try {
            jTextArea1.print();
        } catch (PrinterException ex) {
            Logger.getLogger(Discharge.class.getName()).log(Level.SEVERE, null, ex);
            clear();
        }
    }//GEN-LAST:event_ButtonprintActionPerformed

    private void ButtonclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonclearActionPerformed
        clear();
    }//GEN-LAST:event_ButtonclearActionPerformed

    private void ButtonfeatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonfeatchActionPerformed
        int pid = Integer.parseInt(txtpid.getText());

        try {
            Database db = new Database();
            PreparedStatement stmt = db.con.prepareStatement("SELECT age, bloodgroup FROM patient WHERE pid = ?");
            stmt.setInt(1, pid);

            ResultSet rs = stmt.executeQuery();

            if (rs.next()) {

                int age = rs.getInt("age");
                String bloodgroup = rs.getString("bloodgroup");

                txtage.setText(String.valueOf(age));
                txtbloodgroup.setText(bloodgroup);
            } else {
                JOptionPane.showMessageDialog(null, "No patient record found for the given ID.");
            }

            rs.close();
            stmt.close();
            db.con.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }

        try {
            Database db = new Database();
            PreparedStatement stmt = db.con.prepareStatement("SELECT * FROM admit WHERE pid = ?");
            stmt.setInt(1, pid);
            ResultSet rs = stmt.executeQuery();

            if (rs.next()) {
                // Retrieve the values from the result set
                String pname = rs.getString("pname");
                String surgery = rs.getString("surgery");
                String surgeryamount = rs.getString("surgeryamount");
                String roomtype = rs.getString("roomtype");
                String roomrent = rs.getString("roomrent");
                String date = rs.getString("date");
                int days = rs.getInt("days");
                String dname = rs.getString("dname");

                txtname.setText(pname);
                txtsurgerytype.setText(surgery);
                txtsurgeryamount.setText(surgeryamount);
                txtroomtype.setText(roomtype);
                txtroomrent.setText(roomrent);
                Datechooserdate.setText(date);
                txtdays.setText(String.valueOf(days));
                txtdoctorname.setText(dname);

            } else {
                JOptionPane.showMessageDialog(null, "No admission record found for the given Patient ID.");
                clear();
            }

            rs.close();
            stmt.close();
            db.con.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }

        String dname = txtdoctorname.getText();

        try {
            Database db = new Database();
            PreparedStatement stmt = db.con.prepareStatement("SELECT fee FROM doctor WHERE dname = ?");
            stmt.setString(1, dname);

            ResultSet rs = stmt.executeQuery();

            if (rs.next()) {

                String fee = rs.getString("fee");

                txtconsultantfee1.setText(fee);
            } else {
                JOptionPane.showMessageDialog(null, "No patient record found for the given ID.");
            }

            rs.close();
            stmt.close();
            db.con.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_ButtonfeatchActionPerformed

    private void DatechooserdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DatechooserdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DatechooserdateActionPerformed

    private void txtconsultantfee1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtconsultantfee1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtconsultantfee1ActionPerformed

    private void txtdaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdaysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdaysActionPerformed

    private void ButtonhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonhomeActionPerformed
        new ReceptionistDashBoard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ButtonhomeActionPerformed

    public void featch() {

        try {
            String input = txtpid.getText().trim();
            if (input.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter the patient ID");
            } else {
                int pid = Integer.parseInt(input);

                Database db = new Database();
                String query = "SELECT pname, age, bloodgroup FROM patient WHERE pid=?";
                PreparedStatement pst = db.con.prepareStatement(query);
                pst.setInt(1, pid);

                ResultSet rs = pst.executeQuery();
                if (rs.next()) {
                    String pname = rs.getString("pname");
                    int age = rs.getInt("age");
                    String bloodGroup = rs.getString("bloodgroup");

                    txtname.setText(pname);
                    txtage.setText(String.valueOf(age));
                    txtbloodgroup.setText(bloodGroup);
                } else {
                    JOptionPane.showMessageDialog(this, "Patient not registered");
                }

                rs.close();
                pst.close();
                db.con.close();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid patient ID");
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Discharge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Discharge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Discharge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Discharge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Discharge().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buttonclear;
    private javax.swing.JButton Buttonfeatch;
    private javax.swing.JButton Buttonhome;
    private javax.swing.JButton Buttonprint;
    private javax.swing.JButton Buttonreport;
    private javax.swing.JTextField Datechooserdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField txtage;
    private javax.swing.JTextField txtbloodgroup;
    private javax.swing.JTextField txtconsultantfee1;
    private javax.swing.JTextField txtdays;
    private javax.swing.JTextField txtdoctorname;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtpid;
    private javax.swing.JTextField txtroomrent;
    private javax.swing.JTextField txtroomtype;
    private javax.swing.JTextField txtsurgeryamount;
    private javax.swing.JTextField txtsurgerytype;
    // End of variables declaration//GEN-END:variables
}
