
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author GAURAV
 */
public class UpdatePatient extends javax.swing.JFrame {

    /**
     * Creates new form UpdatePatient
     */
    public UpdatePatient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txtfathersname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtage = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtaddress = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtphoneno = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        cmbmaritialstatus = new javax.swing.JComboBox<>();
        txtdisease = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        cmbcghsprivate = new javax.swing.JComboBox<>();
        Buttonview = new javax.swing.JButton();
        Buttonupdate = new javax.swing.JButton();
        Buttondelete = new javax.swing.JButton();
        Buttonclear = new javax.swing.JButton();
        Buttonhome = new javax.swing.JButton();
        txtpid = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cmbbloodgroup = new javax.swing.JComboBox<>();
        cmbgender = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("HOSPITAL MANAGEMENT SYSTEM");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(" UPDATE PATIENT  ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(329, 329, 329)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(434, 434, 434)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("PATIENT INFORMATION ");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("NAME");

        txtname.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        txtfathersname.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("FATHER'S NAME");

        txtage.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtageKeyPressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("DISEASE");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("BLOOD GROUP");

        txtaddress.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("ADDRESS");

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("PHONE NO.");

        txtphoneno.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtphoneno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtphonenoActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("EMAIL ID ");

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("AGE");

        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("GENDER");

        txtemail.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 51, 51));
        jLabel18.setText("MARITIAL STATUSN ");

        cmbmaritialstatus.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cmbmaritialstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "   <SELECT>", "MARRIED", "UNMARRID" }));

        txtdisease.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jLabel19.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19.setText("CGHS/PRIVATE");

        cmbcghsprivate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cmbcghsprivate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "   <SELECT>", "CGHS", "PRIVATE" }));
        cmbcghsprivate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbcghsprivateActionPerformed(evt);
            }
        });

        Buttonview.setBackground(new java.awt.Color(51, 51, 51));
        Buttonview.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Buttonview.setForeground(new java.awt.Color(255, 255, 255));
        Buttonview.setText("VIEW");
        Buttonview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonviewActionPerformed(evt);
            }
        });

        Buttonupdate.setBackground(new java.awt.Color(51, 51, 51));
        Buttonupdate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Buttonupdate.setForeground(new java.awt.Color(255, 255, 255));
        Buttonupdate.setText("UPDATE");
        Buttonupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonupdateActionPerformed(evt);
            }
        });

        Buttondelete.setBackground(new java.awt.Color(51, 51, 51));
        Buttondelete.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Buttondelete.setForeground(new java.awt.Color(255, 255, 255));
        Buttondelete.setText("DELETE");
        Buttondelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtondeleteActionPerformed(evt);
            }
        });

        Buttonclear.setBackground(new java.awt.Color(51, 51, 51));
        Buttonclear.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Buttonclear.setForeground(new java.awt.Color(255, 255, 255));
        Buttonclear.setText("CLEAR");
        Buttonclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonclearActionPerformed(evt);
            }
        });

        Buttonhome.setBackground(new java.awt.Color(51, 51, 51));
        Buttonhome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Buttonhome.setForeground(new java.awt.Color(255, 255, 255));
        Buttonhome.setText("HOME");
        Buttonhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonhomeActionPerformed(evt);
            }
        });

        txtpid.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("PID");

        cmbbloodgroup.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cmbbloodgroup.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " <SELECT>", "A+", "A-", "O+", "O-", "B+", "B-", "AB+", "AB-" }));

        cmbgender.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cmbgender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "   <SELECT>", "MALE", "FEMALE", "OTHER" }));
        cmbgender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbgenderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(370, 370, 370)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(491, 491, 491)
                                .addComponent(jLabel18))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(36, 36, 36)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtfathersname, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(446, 446, 446))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(171, 171, 171)
                                                .addComponent(txtpid, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel7))
                                        .addGap(179, 179, 179)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jLabel14))
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(70, 70, 70)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtage, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtdisease, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbcghsprivate, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addGap(41, 41, 41)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtphoneno, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(cmbbloodgroup, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(175, 175, 175)
                                            .addComponent(jLabel16)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cmbgender, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(704, 704, 704)
                                .addComponent(cmbmaritialstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(Buttonview)
                        .addGap(63, 63, 63)
                        .addComponent(Buttonupdate)
                        .addGap(64, 64, 64)
                        .addComponent(Buttondelete)
                        .addGap(53, 53, 53)
                        .addComponent(Buttonclear)
                        .addGap(65, 65, 65)
                        .addComponent(Buttonhome)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbcghsprivate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel14))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel7))
                                    .addComponent(txtpid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txtfathersname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(txtdisease, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel8)
                            .addComponent(cmbbloodgroup, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbgender, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(cmbmaritialstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtphoneno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))))
                .addContainerGap(131, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Buttonhome)
                    .addComponent(Buttonclear)
                    .addComponent(Buttondelete)
                    .addComponent(Buttonupdate)
                    .addComponent(Buttonview))
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonviewActionPerformed
        if (txtpid.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter Patient ID");
            return;
        }
        int pid = Integer.parseInt(txtpid.getText());

        try {
            Database db = new Database();
            PreparedStatement stmt = db.con.prepareStatement("SELECT * FROM patient WHERE pid = ?");
            stmt.setInt(1, pid);
            ResultSet rs = stmt.executeQuery();

            if (rs.next()) {
                txtname.setText(rs.getString(2));
                txtfathersname.setText(rs.getString(3));
                cmbbloodgroup.setSelectedItem(rs.getString(4));
                txtaddress.setText(rs.getString(5));
                txtphoneno.setText(rs.getString(6));

                txtemail.setText(rs.getString(7));
                cmbcghsprivate.setSelectedItem(rs.getString(8));
                txtdisease.setText(rs.getString(9));
                txtage.setText(rs.getString(10));
                cmbgender.setSelectedItem(rs.getString(11));
                cmbmaritialstatus.setSelectedItem(rs.getString(12));

            } else {
                JOptionPane.showMessageDialog(null, "PATIENT ID NOT FOUND.");
            }

            rs.close();
            stmt.close();
            db.con.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_ButtonviewActionPerformed

    private void ButtonupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonupdateActionPerformed
        if (txtpid.getText().isEmpty() || txtname.getText().isEmpty() || txtfathersname.getText().isEmpty()
                || txtaddress.getText().isEmpty() || txtphoneno.getText().isEmpty() || txtemail.getText().isEmpty()
                || txtdisease.getText().isEmpty() || txtage.getText().isEmpty() || cmbgender.getSelectedIndex() == 0
                || cmbmaritialstatus.getSelectedIndex() == 0 || cmbbloodgroup.getSelectedIndex() == 0
                || cmbcghsprivate.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "One or more fields are empty.");
            return;
        }

        try {
            int pid = Integer.parseInt(txtpid.getText());
            String pname = txtname.getText();
            String fathersname = txtfathersname.getText();
            String bloodgroup = cmbbloodgroup.getSelectedItem().toString();
            String address = txtaddress.getText();
            String phoneno = txtphoneno.getText();
            String emailid = txtemail.getText();
            String cghs_private = cmbcghsprivate.getSelectedItem().toString();
            String disease = txtdisease.getText();
            int age = Integer.parseInt(txtage.getText());

            String gender = cmbgender.getSelectedItem().toString();
            String maritialstatus = cmbmaritialstatus.getSelectedItem().toString();

            if (txtage.getText().trim().isEmpty() || cmbmaritialstatus.getSelectedIndex() == 0 || cmbgender.getSelectedIndex() == 0 || cmbbloodgroup.getSelectedIndex() == 0 || txtname.getText().trim().isEmpty() || txtfathersname.getText().trim().isEmpty() || txtaddress.getText().trim().isEmpty() || txtphoneno.getText().trim().isEmpty() || cmbcghsprivate.getSelectedIndex() == 0 || txtemail.getText().trim().isEmpty() || txtdisease.getText().trim().isEmpty()) {

                JOptionPane.showMessageDialog(this, "One or more fields are empty");
            } else {
                try {
                    Database db = new Database();
                    String query = "UPDATE patient SET pname=?, fathersname=?, bloodgroup=?, address=?, phoneno=?, emailid=?, cghs_private=?, disease=?, age=?, gender=?, maritialstatus=? WHERE pid=?";
                    PreparedStatement pst = db.con.prepareStatement(query);
                    pst.setString(1, pname);
                    pst.setString(2, fathersname);
                    pst.setString(3, bloodgroup);
                    pst.setString(4, address);
                    pst.setString(5, phoneno);
                    pst.setString(6, emailid);
                    pst.setString(7, cghs_private);
                    pst.setString(8, disease);
                    pst.setInt(9, age);
                    pst.setString(10, gender);
                    pst.setString(11, maritialstatus);
                    pst.setInt(12, pid);

                    int affectedRows = pst.executeUpdate();
                    if (affectedRows == 1) {
                        JOptionPane.showMessageDialog(this, "Update successful");
                    } else {
                        JOptionPane.showMessageDialog(null, "Something went wrong");
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_ButtonupdateActionPerformed

    private void ButtondeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtondeleteActionPerformed
        if (txtpid.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter Patient ID");
            return;
        }

        try {
            int pid = Integer.parseInt(txtpid.getText());

            Database db = new Database();
            String query = "DELETE FROM patient WHERE pid=?";
            PreparedStatement pst = db.con.prepareStatement(query);
            pst.setInt(1, pid);

            int affectedRows = pst.executeUpdate();
            if (affectedRows == 1) {
                JOptionPane.showMessageDialog(this, "Patient deleted successfully");
                txtname.setText("");
                txtfathersname.setText("");
                txtaddress.setText("");
                txtphoneno.setText("");
                txtemail.setText("");
                txtdisease.setText("");
                txtage.setText("");
                cmbgender.setSelectedIndex(0);
                cmbmaritialstatus.setSelectedIndex(0);
                cmbbloodgroup.setSelectedIndex(0);
                cmbcghsprivate.setSelectedIndex(0);

            } else {
                JOptionPane.showMessageDialog(this, "Failed to delete patient");
            }

            pst.close();
            db.con.close();
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_ButtondeleteActionPerformed

    private void ButtonclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonclearActionPerformed
        txtpid.setText("");
        txtname.setText("");
        txtfathersname.setText("");
        txtaddress.setText("");
        txtphoneno.setText("");
        txtemail.setText("");
        txtdisease.setText("");
        txtage.setText("");
        cmbgender.setSelectedIndex(0);
        cmbmaritialstatus.setSelectedIndex(0);
        cmbbloodgroup.setSelectedIndex(0);
        cmbcghsprivate.setSelectedIndex(0);

    }//GEN-LAST:event_ButtonclearActionPerformed

    private void ButtonhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonhomeActionPerformed
        new ReceptionistDashBoard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ButtonhomeActionPerformed

    private void txtphonenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtphonenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtphonenoActionPerformed

    private void cmbcghsprivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbcghsprivateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbcghsprivateActionPerformed

    private void cmbgenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbgenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbgenderActionPerformed

    private void txtageKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtageKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtage.setEditable(true);
            return;
        }
        if (!(evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9')) {
            txtage.setEditable(false);
        } else {
            txtage.setEditable(true);
        }            // TODO add your handling code here:
    }//GEN-LAST:event_txtageKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdatePatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdatePatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdatePatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdatePatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdatePatient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buttonclear;
    private javax.swing.JButton Buttondelete;
    private javax.swing.JButton Buttonhome;
    private javax.swing.JButton Buttonupdate;
    private javax.swing.JButton Buttonview;
    private javax.swing.JComboBox<String> cmbbloodgroup;
    private javax.swing.JComboBox<String> cmbcghsprivate;
    private javax.swing.JComboBox<String> cmbgender;
    private javax.swing.JComboBox<String> cmbmaritialstatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtage;
    private javax.swing.JTextField txtdisease;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtfathersname;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtphoneno;
    private javax.swing.JTextField txtpid;
    // End of variables declaration//GEN-END:variables
}
